### ISSUE TITLE
Images appear blue

### ISSUE THREAD

**Issue by prossir** [DimaMishchenko/ExpandableButton#1] opened 2018-11-04 22:25 UTC
Hello @DimaMishchenko ,

When I use your library the icons i use change from sand (color) to blue. Do you now why? Otherwise all is cool and working as expected. 

Thank you.

**Comment by DimaMishchenko** [comment] 2018-11-05 09:57
Hello @AntaresR, 
Thank you for your issue. Unfortunately I can't reproduce this behavior. Can you please provide example of code where you setup `ExpandableButton` and `ExpandableButtonItems`. And example of image that you use.

**Comment by prossir** [comment] 2018-11-11 05:17
@DimaMishchenko I solve it using . alwaysOriginal

`
            ExpandableButtonItem(
                image: UIImage(named: "ic_arkit_sand")?.withRenderingMode(.alwaysOriginal),
                highlightedImage: UIImage(named: "ic_arkit_sand")?.withRenderingMode(.alwaysOriginal),
                attributedTitle: NSAttributedString( string: "AR", attributes: [.foregroundColor: UIColor.black, .font: UIFont.systemFont(ofSize: 12)]),
                highlightedAttributedTitle: NSAttributedString( string: "AR", attributes: [.foregroundColor: UIColor.black, .font: UIFont.systemFont(ofSize: 12)]),
                contentEdgeInsets: UIEdgeInsets(top: 6, left: 6, bottom: 6, right: 6),
                titleEdgeInsets: title_insets,
                imageEdgeInsets: image_insets,
                size: cell_size,
                titleAlignment: .center,
                imageContentMode: .scaleAspectFit,
                action: { _ in
                    print("ic_augment danger")
            })
`

Thanks for your interest.

**Comment by DimaMishchenko** [comment] 2018-11-12 11:16
Closing issue. If you have any more questions feel free to open new issue.

**Closed as completed by DimaMishchenko** 2018-11-12 11:16 UTC
